<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_fa fa-bars</name>
   <tag></tag>
   <elementGuidId>48a46700-fb95-4f6d-b808-6a6ea74d5b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-toggle']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>058f54e7-c79c-4073-878f-ee18d19f6b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars</value>
      <webElementGuid>f89ca161-efa9-4c1e-bd0b-892e643416b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-toggle&quot;)/i[@class=&quot;fa fa-bars&quot;]</value>
      <webElementGuid>a6d15eb0-32f3-43cf-a351-ec5303b4015c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu-toggle']/i</value>
      <webElementGuid>c5ed412e-37cd-4e28-b0e0-caca1471ffae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>637405aa-299f-482c-8823-76fbf9d63d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
